import 'package:flutter/material.dart';

List iconData = [
  Icon(Icons.home),
  Icon(Icons.abc_sharp),
  Icon(Icons.ice_skating),
  Icon(Icons.schedule),
  Icon(Icons.school),
  Icon(Icons.timelapse),
  Icon(Icons.book),
  Icon(Icons.play_lesson_outlined),
  Icon(Icons.play_arrow),
  Icon(Icons.person),
  Icon(Icons.email),
  Icon(Icons.password),
  Icon(Icons.key),
  Icon(Icons.pending),
  Icon(Icons.food_bank),
  Icon(Icons.person),
  Icon(Icons.grade),
  Icon(Icons.computer),
  Icon(Icons.android),
  Icon(Icons.apple),
  Icon(Icons.swipe_left_alt),
  Icon(Icons.umbrella),
  Icon(Icons.close),
  Icon(Icons.favorite),
  Icon(Icons.beach_access),
  Icon(Icons.ac_unit),
  Icon(Icons.alarm),
  Icon(Icons.access_time),
  Icon(Icons.photo),
  Icon(Icons.album),
  Icon(Icons.location_city),
  Icon(Icons.add),
];
